title: Adaptive Characteristic Mapping Method for the Euler Equations (CM2E)
position: <a href=" https://anr.fr/Projet-ANR-20-CE46-0010">Project ANR-20-CE46-0010</a>
affiliation: 2021 - 2024
email:
description:
keywords: Computational Physics, Numerical Analysis
google_scholar:
github_link: https://github.com/CharacteristicMappingMethod
avatar: ./assets/img/arton1807.jpg
favicon: ./assets/img/arton1807.jpg
favicon_dark: ./assets/img/arton1807.jpg
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
baseurl: "/characteristicmappingmethod.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: philipp137

# Build settings
#theme: minima
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
